# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: 'mongo'
    container_name: "rest-api"
    environment: 
      - MONGO_INITDB_DATABASE=rest-api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rest-api
    ports:
      - "27017:27017"